(() => {
'use strict';

const root = document.getElementById('game');
const TOPICS = ['Fondations','Fractions','Puissances','Équations','Fonctions','Dérivation','Suites','Exp / Ln','Trigonométrie','Probabilités','Vecteurs','Limites','Intégrales'];
const SHORT = {'Fondations':'BASE','Fractions':'FRAC','Puissances':'POW','Équations':'EQ','Fonctions':'FONC','Dérivation':'DÉRIV','Suites':'SUITES','Exp / Ln':'EXP·LN','Trigonométrie':'TRIGO','Probabilités':'PROBA','Vecteurs':'VECT','Limites':'LIMIT','Intégrales':'INT'};
const UNLOCK = {'Fondations':1,'Fractions':1,'Puissances':1,'Équations':1,'Fonctions':2,'Dérivation':3,'Suites':4,'Exp / Ln':8,'Probabilités':10,'Trigonométrie':13,'Vecteurs':16,'Limites':19,'Intégrales':24};
const BOSSES = {
  'Fondations':['CAPITAINE CALCUL','Le gardien du vieux royaume des automatismes.'],
  'Fractions':['FRACTIONNAIRE','Il coupe tout en morceaux. Même ton chrono.'],
  'Puissances':['L’EXPOSANT','Petit chiffre en haut, gros problèmes en bas.'],
  'Équations':['X-TERMINATEUR','Il ne s’arrête que quand x est isolé.'],
  'Fonctions':['IMAGEUR','Il transforme tout ce qui entre dans son domaine.'],
  'Dérivation':['DÉRIVATOR','Tu peux fuir, mais il connaît ta pente.'],
  'Suites':['RÉCURSATOR','Il revient. Puis revient. Puis revient encore.'],
  'Exp / Ln':['LORD LOGARITHME','Il adore les produits… surtout quand ils deviennent des sommes.'],
  'Trigonométrie':['SINISTRE SINUS','Il tourne en rond, mais connaît exactement ses angles.'],
  'Probabilités':['PROBABILL','Il avait une chance sur deux de venir. Mauvaise nouvelle.'],
  'Vecteurs':['VECTERROR','Direction, sens, norme : il n’oublie rien.'],
  'Limites':['LE GRAND INFINI','À la limite, il gagne. Sauf si tu calcules plus vite.'],
  'Intégrales':['INTÉGRALATOR','Il additionne de minuscules dégâts sous la courbe.']
};
const SKINS = {
  'Apprenti':{price:0,body:'#d6d3c8',accent:'#b58b4a',cape:'#675745'},
  'Mage des dérivées':{price:350,body:'#b9a8d8',accent:'#6f52a4',cape:'#352c5a'},
  'Chevalier cosinus':{price:650,body:'#c8d7e8',accent:'#49749e',cape:'#263b55'},
  'Alchimiste logarithme':{price:900,body:'#b8d2b5',accent:'#4f7f55',cape:'#29472d'},
  '30/30 légendaire':{price:2200,body:'#f1ddb0',accent:'#b78a2e',cape:'#5e4519'}
};
const ACHIEVEMENTS = {
  first:{name:'Premier coup',desc:'Répondre correctement à une première question.',coins:25},
  combo10:{name:'Combo décimal',desc:'Atteindre un combo ×10.',coins:75},
  q100:{name:'Centurion mental',desc:'Jouer 100 questions.',coins:100},
  boss5:{name:'Chasseur de symboles',desc:'Vaincre 5 boss.',coins:150},
  sprintA:{name:'Chronomage',desc:'Obtenir au moins 24/30 en Course.',coins:180},
  perfect:{name:'30/30 légendaire',desc:'Réaliser un 30/30 en 9 minutes.',coins:500}
};
const GOOD = ['Exact. Le boss vient de perdre le fil de son raisonnement.','Propre. Même la calculatrice aurait applaudi — si elle était autorisée.','Pas besoin d’intégrer la panique.','Ça passe crème. Mathématiquement, évidemment.','Combo validé : tu viens de dériver le danger.'];
const BAD = ['Tu as dérivé. Reviens à la tangente.','Cette réponse avait une probabilité… un peu trop faible.','X n’est pas encore isolé. Le boss, lui, oui.','Erreur de calcul : l’ennemi caché classique.','À la limite, on recommence.'];
const KEYWORDS = {
  'Fondations':['calcul','mental','priorité','decimal','décimal','pourcent','proportion','identité remarquable'],
  'Fractions':['fraction','dénominateur','numerateur','numérateur','quotient'],
  'Puissances':['puissance','exposant','racine','sqrt'],
  'Équations':['équation','equation','résoudre','resoudre','inégalité','inequation','inconnue'],
  'Fonctions':['fonction','image','antécédent','antecedent','courbe','variation','affine'],
  'Dérivation':['dériv','deriv','tangente','f\'','dérivée'],
  'Suites':['suite','u_n','un+1','récurrence','recurrence','arithmétique','géométrique'],
  'Exp / Ln':['exponentielle','logarithme','ln','exp(','e^'],
  'Trigonométrie':['sin','cos','trigono','radian','cercle trigonométrique'],
  'Probabilités':['probab','binomiale','bernoulli','espérance','conditionnelle','indépendant'],
  'Vecteurs':['vecteur','scalaire','norme','orthogonal','colinéaire','coordonnées'],
  'Limites':['limite','+∞','-∞','infini','asymptote'],
  'Intégrales':['intégrale','integrale','primitive','aire sous','équation différentielle','differentielle']
};

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const pick=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b];}return a||1;};
const frac=(n,d=1)=>{if(d===0)return {n:0,d:1}; if(d<0){n=-n;d=-d;} const g=gcd(n,d);return {n:n/g,d:d/g};};
const addF=(a,b)=>frac(a.n*b.d+b.n*a.d,a.d*b.d);
const mulF=(a,b)=>frac(a.n*b.n,a.d*b.d);
const divF=(a,b)=>frac(a.n*b.d,a.d*b.n);
const fmtF=f=>f.d===1?String(f.n):`${f.n}/${f.d}`;
const fmtN=n=>{if(typeof n==='object'&&n&&'n'in n)return fmtF(n);if(typeof n==='number'){if(Math.abs(n-Math.round(n))<1e-9)return String(Math.round(n));return Number(n.toFixed(3)).toString().replace('.',',');}return String(n);};
const escapeHTML=s=>String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function makeOptions(correct,distractors){
  const c=fmtN(correct), out=[];
  [correct,...distractors].forEach(x=>{const s=fmtN(x);if(!out.includes(s))out.push(s);});
  const fallback=['0','1','−1','2','1/2','aucune de ces réponses'];
  fallback.forEach(x=>{if(out.length<4&&!out.includes(x))out.push(x);});
  while(out.length<4){const x=String(rand(-9,12));if(!out.includes(x))out.push(x);}
  const opts=shuffle(out.slice(0,4)); return {opts,idx:opts.indexOf(c)};
}
function makeTextOptions(correct,distractors){return makeOptions(String(correct),distractors.map(String));}

function schoolWeek(){const d=new Date();const m=d.getMonth()+1; if(m===7||m===8)return 36; const y=d.getFullYear();const start=new Date(m>=9?y:y-1,8,1);return clamp(Math.floor((d-start)/604800000)+1,1,36);}
function defaults(){
  const mastery={},attempts={},correct={};TOPICS.forEach(t=>{mastery[t]=UNLOCK[t]<=4?.38:.28;attempts[t]=0;correct[t]=0;});
  return {xp:0,coins:0,level:1,streakBest:0,skin:'Apprenti',ownedSkins:['Apprenti'],mastery,attempts,correct,weeklyTopics:['Fondations','Fractions','Équations'],schoolWeek:schoolWeek(),bestSprint:0,bossWins:0,totalQuestions:0,achievements:[],sound:true,tutorialSeen:false,lastControlName:''};
}
function loadSave(){const d=defaults();try{const x=JSON.parse(localStorage.getItem('mathQuestTerminalSave')||'{}');Object.assign(d,x);['mastery','attempts','correct'].forEach(k=>TOPICS.forEach(t=>{if(d[k][t]==null)d[k][t]=defaults()[k][t];}));if(!Array.isArray(d.ownedSkins))d.ownedSkins=['Apprenti'];if(!Array.isArray(d.achievements))d.achievements=[];return d;}catch(e){return d;}}
let save=loadSave();
function persist(){try{localStorage.setItem('mathQuestTerminalSave',JSON.stringify(save));}catch(e){}}

function qFoundations(d){const typ=rand(0,4),s=2+d*2;let q,c,ds,ex;if(typ===0){const a=rand(2,s+5),b=rand(2,s+5),cc=rand(2,s+5);c=a+b*cc;q=`Calculer mentalement : ${a} + ${b} × ${cc}`;ds=[(a+b)*cc,a+b+cc,a*b+cc];ex='Priorité à la multiplication : on calcule le produit avant l’addition.';}else if(typ===1){const a=pick([20,24,28,32,36,40,48,60,72,80,84,96]),p=pick([10,20,25,50,75]);c=a*p/100;q=`${p} % de ${a} vaut…`;ds=[a/(p||1),a*(1+p/100),p/a];ex=`${p}% = ${p}/100 : on multiplie ${a} par ${p}/100.`;}else if(typ===2){const a=rand(10,35),b=rand(2,9);c=(a+b)*(a-b);q=`Calculer vite : (${a}+${b})(${a}−${b})`;ds=[a*a+b*b,a*a-b,a-b*b];ex='Identité remarquable : (a+b)(a−b)=a²−b².';}else if(typ===3){const a=rand(2,12),b=rand(2,12);c=(a+b)**2;q=`Calculer : (${a}+${b})²`;ds=[a*a+b*b,a*a+2*a+b*b,a*a+2*b+b*b];ex='(a+b)²=a²+2ab+b².';}else{const x=rand(-8,8),a=pick([-5,-3,-2,2,3,4,5]),b=rand(-9,9);c=a*x+b;q=`Calculer ${a}×${x} ${b>=0?'+':'−'} ${Math.abs(b)}`;ds=[a*(x+b),a*x-b,x+b];ex='Garde les signes sous contrôle et calcule le produit avant la somme.';}const o=makeOptions(c,ds);return {q,...o,ex};}
function qFractions(d){const typ=rand(0,3);let q,c,ds,ex;if(typ===0){const a=frac(rand(1,8),rand(2,9)),b=frac(rand(1,8),rand(2,9));c=addF(a,b);q=`${fmtF(a)} + ${fmtF(b)} = ?`;ds=[frac(a.n+b.n,a.d+b.d),frac(a.n*b.d-b.n*a.d,a.d*b.d),mulF(a,b)];ex='Addition : même dénominateur, puis addition des numérateurs.';}else if(typ===1){const a=frac(rand(1,9),rand(2,10)),b=frac(rand(1,9),rand(2,10));c=mulF(a,b);q=`${fmtF(a)} × ${fmtF(b)} = ?`;ds=[frac(a.n+b.n,a.d+b.d),frac(a.n*b.d,a.d*b.n),frac(a.n*b.n,a.d+b.d)];ex='Produit : numérateur×numérateur et dénominateur×dénominateur, puis simplifier.';}else if(typ===2){const a=frac(rand(1,8),rand(2,9)),b=frac(rand(1,8),rand(2,9));c=divF(a,b);q=`${fmtF(a)} ÷ ${fmtF(b)} = ?`;ds=[mulF(a,b),frac(a.n+b.n,a.d+b.d),frac(a.d*b.n,a.n*b.d)];ex='Diviser par une fraction revient à multiplier par son inverse.';}else{const den=pick([2,4,5,8,10,20,25]),num=rand(1,den-1),f=frac(num,den);c=f.n/f.d;q=`Écriture décimale de ${fmtF(f)} ?`;ds=[c*10,c/10,1-c];ex='Repère les fractions usuelles et simplifie avant de convertir.';}const o=makeOptions(c,ds);return {q,...o,ex};}
function qPowers(d){const typ=rand(0,4);let q,c,ds,ex;if(typ===0){const a=rand(2,6),m=rand(2,4+d),n=rand(1,4);c=`${a}^${m+n}`;q=`${a}^${m} × ${a}^${n} = ?`;ds=[`${a}^${m*n}`,`${a}^${m-n}`,`${a*a}^${m+n}`];ex='Même base dans un produit : on additionne les exposants.';}else if(typ===1){const a=rand(2,5),m=rand(3,8),n=rand(1,m-1);c=`${a}^${m-n}`;q=`${a}^${m} ÷ ${a}^${n} = ?`;ds=[`${a}^${m+n}`,`${a}^${m*n}`,`${a}^${n-m}`];ex='Même base dans un quotient : on soustrait les exposants.';}else if(typ===2){const n=pick([4,9,16,25,36,49,64,81,100,121,144,169]);c=Math.sqrt(n);q=`√${n} = ?`;ds=[c+1,c-1,n/2];ex='Connais les carrés parfaits usuels.';}else if(typ===3){const a=rand(2,6),m=rand(2,4),n=rand(2,4);c=`${a}^${m*n}`;q=`(${a}^${m})^${n} = ?`;ds=[`${a}^${m+n}`,`${a*n}^${m}`,`${a}^${m-n}`];ex='Puissance d’une puissance : on multiplie les exposants.';}else{const n=rand(2,5);c=`1/${n}^3`;q=`${n}^(−3) = ?`;ds=[`${n}^3`,`−${n}^3`,`1/${n}^2`];ex='Un exposant négatif inverse : a^(−n)=1/a^n.';}const o=makeTextOptions(c,ds);return {q,...o,ex};}
function qEquations(d){const typ=rand(0,3);let q,c,ds,ex;if(typ<3){const x=rand(-8,8),a=pick([-7,-5,-3,-2,2,3,4,5,6]),b=rand(-12,12),cc=a*x+b;c=x;q=`Résoudre : ${a}x ${b>=0?'+':'−'} ${Math.abs(b)} = ${cc}`;ds=[x+1,x-1,-x];ex='Isole x : enlève le terme constant puis divise par le coefficient.';}else{const r=rand(-6,6),a=rand(2,8);c=r;q=`Une solution de (x ${-r>=0?'+':'−'} ${Math.abs(-r)})(x + ${a}) = 0 est…`;ds=[-a,a,-r];ex='Produit nul : un des facteurs est nul.';}const o=makeOptions(c,ds);return {q,...o,ex};}
function qFunctions(d){const typ=rand(0,3);let q,c,ds,ex;if(typ===0){const a=pick([-5,-4,-3,-2,2,3,4,5]),b=rand(-8,8),x=rand(-5,5);c=a*x+b;q=`Si f(x)=${a}x ${b>=0?'+':'−'} ${Math.abs(b)}, alors f(${x}) = ?`;ds=[a+b*x,c+a,c-b];ex='Une image se calcule en remplaçant x par la valeur donnée.';}else if(typ===1){const a=pick([-5,-4,-3,-2,2,3,4,5]),b=rand(-6,6),x=rand(-5,5),y=a*x+b;c=x;q=`f(x)=${a}x ${b>=0?'+':'−'} ${Math.abs(b)}. Résoudre f(x)=${y}.`;ds=[x+1,-x,x-1];ex='Chercher un antécédent revient à résoudre une équation.';}else if(typ===2){const a=pick([-6,-4,-2,2,4,6]);c=a>0?'croissante':'décroissante';q=`La fonction f(x)=${a}x+3 est…`;ds=['constante',a>0?'décroissante':'croissante','sans variation'];ex='Pour ax+b : a>0 → croissante ; a<0 → décroissante.';}else{const a=rand(1,4),r=rand(-4,4);c='minimum';q=`f(x)=${a}(x−${r})²+2 possède en x=${r} un…`;ds=['maximum','point d’inflexion','zéro certain'];ex='Avec un coefficient positif devant le carré, la parabole est tournée vers le haut.';}const o=makeTextOptions(c,ds);return {q,...o,ex};}
function qDerivative(d){const typ=rand(0,4);let q,c,ds,ex;if(typ===0){const a=rand(1,5),b=rand(-6,6),x=rand(-4,4);c=2*a*x+b;q=`f(x)=${a}x² ${b>=0?'+':'−'} ${Math.abs(b)}x + 3. f'(${x}) = ?`;ds=[a*x+b,2*a+b,2*a*x];ex='Dérivée de ax²+bx+c : 2ax+b, puis remplace x.';}else if(typ===1){const n=rand(2,6),a=rand(1,4);c=`${a*n}x^${n-1}`;q=`Dérivée de f(x)=${a}x^${n} ?`;ds=[`${a}x^${n-1}`,`${a*n}x^${n}`,`${n}x^${n-1}`];ex="(x^n)'=n x^(n−1), le coefficient reste multiplicatif.";}else if(typ===2){const a=pick([-5,-4,-3,-2,2,3,4,5]);c=a>0?'croissante':'décroissante';q=`Si f'(x)=${a} sur un intervalle, f y est…`;ds=['constante','positive','nulle'];ex="Le signe de f' détermine les variations de f.";}else if(typ===3){const a=rand(1,5),x=rand(1,4);c=-a/(x*x);q=`f(x)=${a}/x. f'(${x}) = ?`;ds=[a/(x*x),-a/x,a/x];ex="(1/x)'=−1/x².";}else{c='u′v + uv′';q='Dérivée du produit uv ?';ds=['u′v′','u′/v′','u/v²'];ex="Formule : (uv)'=u'v+uv'.";}const o=makeOptions(c,ds);return {q,...o,ex};}
function qSequences(d){const typ=rand(0,4);let q,c,ds,ex;if(typ===0){const u0=rand(-5,8),r=rand(-4,6),n=rand(3,12);c=u0+n*r;q=`Suite arithmétique : u₀=${u0}, raison ${r}. u${n} = ?`;ds=[u0+(n-1)*r,u0*n+r,u0+r];ex='Suite arithmétique : uₙ=u₀+n×r.';}else if(typ===1){const u0=rand(1,5),r=pick([2,3,-2]),n=rand(2,5);c=u0*(r**n);q=`Suite géométrique : u₀=${u0}, raison ${r}. u${n} = ?`;ds=[u0+n*r,u0*(r**(n-1)),(u0*r)**n];ex='Suite géométrique : uₙ=u₀×q^n.';}else if(typ===2){const u=rand(1,9),a=rand(2,5),b=rand(-3,5);c=a*u+b;q=`uₙ=${u} et uₙ₊₁=${a}uₙ ${b>=0?'+':'−'} ${Math.abs(b)}. uₙ₊₁ = ?`;ds=[a+u+b,a*u-b,u+b];ex='Dans une récurrence, remplace directement uₙ par sa valeur.';}else if(typ===3){const r=pick([1.2,1.5,2,0.8,0.5]);c=r>1?'croissante':'décroissante';q=`Une suite géométrique positive de raison ${String(r).replace('.',',')} est…`;ds=['constante','alternée','toujours négative'];ex='Positive : q>1 → croissante ; 0<q<1 → décroissante.';}else{const n=rand(2,7);c=n*(n+1)/2;q=`1 + 2 + … + ${n} = ?`;ds=[n*n,n*(n-1)/2,n+1];ex='Somme des entiers de 1 à n : n(n+1)/2.';}const o=makeOptions(c,ds);return {q,...o,ex};}
function qExpLn(d){const typ=rand(0,5);let q,c,ds,ex;if(typ===0){const a=rand(-4,6),b=rand(-4,6);c=`e^${a+b}`;q=`e^${a} × e^${b} = ?`;ds=[`e^${a*b}`,`e^${a-b}`,`e^${a}+e^${b}`];ex='e^a×e^b=e^(a+b).';}else if(typ===1){const a=rand(-6,8);c=a;q=`ln(e^${a}) = ?`;ds=[a+1,-a,Math.round(Math.E*a)];ex='ln et exp sont réciproques : ln(e^a)=a.';}else if(typ===2){const a=rand(-5,7);c=a;q=`Résoudre e^x = e^${a}.`;ds=[-a,a+1,a-1];ex='L’exponentielle est injective : mêmes images, mêmes exposants.';}else if(typ===3){const a=rand(2,8),b=rand(2,8);c=`ln(${a*b})`;q=`ln(${a}) + ln(${b}) = ?`;ds=[`ln(${a+b})`,`ln(${Math.abs(a-b)||1})`,`ln(${a})×ln(${b})`];ex='ln(a)+ln(b)=ln(ab), pour a,b>0.';}else if(typ===4){c='e^x';q='La dérivée de e^x est…';ds=['x·e^x','1/e^x','ln(x)'];ex="Formule fondamentale : (e^x)'=e^x.";}else{c='1/x';q='La dérivée de ln(x), pour x>0, est…';ds=['ln(x)','e^x','x'];ex="Formule fondamentale : (ln x)'=1/x.";}const o=makeOptions(c,ds);return {q,...o,ex};}
function qTrig(d){const vals=[['0','1','0'],['π/6','√3/2','1/2'],['π/4','√2/2','√2/2'],['π/3','1/2','√3/2'],['π/2','0','1']],v=pick(vals),typ=rand(0,4);let q,c,ds,ex='Utilise le cercle trigonométrique et les angles remarquables.';if(typ===0){q=`cos(${v[0]}) = ?`;c=v[1];ds=['0','1','1/2','√2/2','√3/2'].filter(x=>x!==c).slice(0,3);}else if(typ===1){q=`sin(${v[0]}) = ?`;c=v[2];ds=['0','1','1/2','√2/2','√3/2'].filter(x=>x!==c).slice(0,3);}else if(typ===2){q='Pour tout x, sin²(x)+cos²(x) = ?';c='1';ds=['0','2','sin(2x)'];ex='Identité fondamentale : sin²x+cos²x=1.';}else if(typ===3){q='cos(x+2π) est égal à…';c='cos(x)';ds=['−cos(x)','sin(x)','−sin(x)'];ex='Sinus et cosinus sont 2π-périodiques.';}else{q='cos(−x) est égal à…';c='cos(x)';ds=['−cos(x)','sin(x)','−sin(x)'];ex='Le cosinus est une fonction paire.';}const o=makeTextOptions(c,ds);return {q,...o,ex};}
function qProbability(d){const typ=rand(0,5);let q,c,ds,ex;if(typ===0){const p=pick([.1,.2,.25,.3,.4,.6,.7,.75,.8,.9]);c=1-p;q=`P(A)=${fmtN(p)}. Alors P(non A)= ?`;ds=[p,1+p,p/2];ex='Événement contraire : P(non A)=1−P(A).';}else if(typ===1){const n=rand(5,20),p=pick([.1,.2,.25,.5,.75]);c=n*p;q=`X suit B(${n}; ${fmtN(p)}). E(X) = ?`;ds=[n+p,n*(1-p),p/n];ex='Pour X~B(n,p), E(X)=np.';}else if(typ===2){const pa=pick([.2,.3,.4,.5,.6]),pb=pick([.2,.4,.5,.7]);c=pa*pb;q=`A et B indépendants, P(A)=${fmtN(pa)}, P(B)=${fmtN(pb)}. P(A∩B)= ?`;ds=[pa+pb,pa/pb,1-c];ex='Indépendance : P(A∩B)=P(A)×P(B).';}else if(typ===3){const p=pick([.2,.3,.4,.6]),cond=pick([.25,.5,.75]),inter=p*cond;c=cond;q=`P(A)=${fmtN(p)} et P(A∩B)=${fmtN(inter)}. P_A(B)= ?`;ds=[inter,p,1-cond];ex='P_A(B)=P(A∩B)/P(A).';}else if(typ===4){const n=rand(4,10),p=pick([.2,.3,.5]);c=n;q=`Dans B(${n}; ${fmtN(p)}), le nombre d’essais est…`;ds=[p,1-p,n*p];ex='Dans B(n,p), n est le nombre d’épreuves.';}else{const p=pick([.2,.3,.4,.6]);c=p*p;q=`Deux succès indépendants, chacun de probabilité ${fmtN(p)} : probabilité des deux succès ?`;ds=[2*p,1-p,p];ex='Deux événements indépendants se multiplient.';}const o=makeOptions(c,ds);return {q,...o,ex};}
function qVectors(d){const typ=rand(0,4);let q,c,ds,ex;if(typ===0){const x1=rand(-5,5),y1=rand(-5,5),x2=rand(-5,5),y2=rand(-5,5);c=x1*x2+y1*y2;q=`u=(${x1};${y1}), v=(${x2};${y2}). u·v = ?`;ds=[x1+x2+y1+y2,x1*x2-y1*y2,c+1];ex='Produit scalaire : xx′+yy′.';}else if(typ===1){const x=rand(-6,6),y=rand(-6,6);c=x*x+y*y;q=`u=(${x};${y}). ||u||² = ?`;ds=[x+y,Math.abs(x)+Math.abs(y),x*x-y*y];ex='||u||²=x²+y².';}else if(typ===2){c='orthogonaux';q='Si u·v=0 avec u et v non nuls, ils sont…';ds=['colinéaires','égaux','opposés'];ex='Produit scalaire nul ⇔ orthogonalité (vecteurs non nuls).';}else if(typ===3){const ax=rand(-4,4),ay=rand(-4,4),bx=rand(-4,4),by=rand(-4,4);c=`(${bx-ax};${by-ay})`;q=`A(${ax};${ay}), B(${bx};${by}). Coordonnées de AB ?`;ds=[`(${ax-bx};${ay-by})`,`(${ax+bx};${ay+by})`,`(${bx};${by})`];ex='AB=(x_B−x_A ; y_B−y_A).';}else{c='0';q='Deux vecteurs orthogonaux ont pour produit scalaire…';ds=['1','−1','leur norme'];ex='Orthogonalité : u·v=0.';}const o=makeOptions(c,ds);return {q,...o,ex};}
function qLimits(d){const typ=rand(0,5);let q,c,ds,ex;if(typ===0){const n=rand(1,5);c='+∞';q=`lim x→+∞ de x^${n} = ?`;ds=['−∞','0','1'];ex='Une puissance positive de x tend vers +∞ quand x→+∞.';}else if(typ===1){c='0';q='lim x→+∞ de 1/x = ?';ds=['+∞','1','−∞'];ex='L’inverse d’un nombre très grand tend vers 0.';}else if(typ===2){c='+∞';q='lim x→+∞ de e^x = ?';ds=['0','1','−∞'];ex='L’exponentielle croît sans borne vers +∞.';}else if(typ===3){c='0';q='lim x→−∞ de e^x = ?';ds=['+∞','−∞','1'];ex='Vers −∞, e^x tend vers 0.';}else if(typ===4){const a=rand(1,6),b=rand(1,6);c=frac(a,b);q=`lim x→+∞ de (${a}x²+1)/(${b}x²−3) = ?`;ds=[a/b+1,0,frac(b,a)];ex='Même degré : limite = rapport des coefficients dominants.';}else{c='+∞';q='lim x→0⁺ de 1/x = ?';ds=['−∞','0','1'];ex='Quand x>0 se rapproche de 0, 1/x devient arbitrairement grand.';}const o=makeOptions(c,ds);return {q,...o,ex};}
function qIntegrals(d){const typ=rand(0,5);let q,c,ds,ex;if(typ===0){const n=rand(1,5);c=`x^${n+1}/${n+1} + C`;q=`Une primitive de x^${n} est…`;ds=[`${n}x^${n-1}`,`x^${n+1}`,`x^${n}/${n}`];ex='Primitive de x^n : x^(n+1)/(n+1)+C, pour n≠−1.';}else if(typ===1){c='e^x + C';q='Une primitive de e^x est…';ds=['x·e^x + C','ln(x)+C','1/e^x+C'];ex='e^x est sa propre dérivée et sa propre primitive.';}else if(typ===2){c='ln(x) + C';q='Sur ]0,+∞[, une primitive de 1/x est…';ds=['1/x²+C','e^x+C','x²/2+C'];ex='Primitive de 1/x : ln(x)+C.';}else if(typ===3){const a=rand(1,5),b=rand(1,5);c=a*(b*b)/2;q=`∫₀^${b} ${a}x dx = ?`;ds=[a*b,a*b*b,a*b*b/3];ex='Primitive de ax : ax²/2, puis valeur en b moins valeur en 0.';}else if(typ===4){c='F(b)−F(a)';q='Si F est une primitive de f, ∫ₐᵇ f(x) dx = ?';ds=['F(a)+F(b)','f(b)−f(a)','F(a)−F(b)'];ex='Théorème fondamental : ∫ₐᵇf = F(b)−F(a).';}else{c='Ce^x';q="Les solutions de y'=y sont de la forme…";ds=['Cx','C/x','Ce^(−x)'];ex="Équation différentielle y'=y : y(x)=Ce^x.";}const o=makeOptions(c,ds);return {q,...o,ex};}
const GEN={'Fondations':qFoundations,'Fractions':qFractions,'Puissances':qPowers,'Équations':qEquations,'Fonctions':qFunctions,'Dérivation':qDerivative,'Suites':qSequences,'Exp / Ln':qExpLn,'Trigonométrie':qTrig,'Probabilités':qProbability,'Vecteurs':qVectors,'Limites':qLimits,'Intégrales':qIntegrals};

let scene='title', currentQ=null, battle=null, timers=[], currentControlDataURL='', currentControlBlob=null;
function clearTimers(){timers.forEach(t=>{clearTimeout(t);clearInterval(t);});timers=[];}
function later(ms,fn){const id=setTimeout(fn,ms);timers.push(id);return id;}
function chooseTopic(forced=null){
  if(forced)return forced;
  const available=TOPICS.filter(t=>UNLOCK[t]<=save.schoolWeek), weights=[];
  available.forEach(t=>{let w=.5+(1.15-(save.mastery[t]||.3))*1.8;if(save.weeklyTopics.includes(t))w*=2.4;if(['Fondations','Fractions','Équations'].includes(t))w*=1.18;weights.push(Math.max(.1,w));});
  const total=weights.reduce((a,b)=>a+b,0);let r=Math.random()*total;
  for(let i=0;i<available.length;i++){r-=weights[i];if(r<=0)return available[i];}
  return available[0];
}
function difficulty(topic){const year=Math.floor((save.schoolWeek-1)/9);const m=save.mastery[topic]||.3;return clamp(1+year+(m>.68?1:0),1,5);}
function newQuestion(forced=null){const topic=chooseTopic(forced), q=GEN[topic](difficulty(topic));return {topic,...q};}
function skin(){return SKINS[save.skin]||SKINS.Apprenti;}
function heroHTML(extra='') {const s=skin();return `<div class="hero ${extra}" style="--body:${s.body};--accent:${s.accent};--cape:${s.cape}"><i class="cape"></i><i class="body"></i><i class="head"></i><i class="hat"></i><i class="eye l"></i><i class="eye r"></i><i class="leg l"></i><i class="leg r"></i><i class="sword"></i></div>`;}
function bossHTML(topic,extra=''){return `<div><div class="boss ${extra}"><i class="horn l"></i><i class="horn r"></i><i class="face"></i><i class="eye l"></i><i class="eye r"></i><b class="glyph">${escapeHTML(SHORT[topic])}</b></div><div class="boss-name">${escapeHTML(BOSSES[topic][0])}</div></div>`;}
function chrome(inner=''){return `<div class="pixel-noise"></div><div class="scanlines"></div>${inner}`;}
function topbar(title,sub=''){return `<header class="topbar"><div><h1>${escapeHTML(title)}</h1>${sub?`<small>${escapeHTML(sub)}</small>`:''}</div><div class="hud">NV ${save.level}<br>${save.xp} XP · ◈ ${save.coins}</div></header>`;}
function showToast(msg,ms=1800){const old=root.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;root.appendChild(el);later(ms,()=>el.remove());}
function modal(title,text,yes='OK',no='',onYes=null){const wrap=document.createElement('div');wrap.className='modal-wrap';wrap.innerHTML=`<div class="modal"><h3>${escapeHTML(title)}</h3><p>${escapeHTML(text)}</p><div class="modal-actions"><button class="game-btn gold" data-modal-yes>${escapeHTML(yes)}</button>${no?`<button class="game-btn" data-modal-no>${escapeHTML(no)}</button>`:''}</div></div>`;root.appendChild(wrap);wrap.querySelector('[data-modal-yes]').addEventListener('click',()=>{wrap.remove();if(onYes)onYes();});const n=wrap.querySelector('[data-modal-no]');if(n)n.addEventListener('click',()=>wrap.remove());}
function beep(freq=440,dur=.08,type='square'){if(!save.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!beep.ctx)beep.ctx=new AC();const ctx=beep.ctx;if(ctx.state==='suspended')ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.045,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+dur);}catch(e){}}
function vibrate(ms=20){try{if(navigator.vibrate)navigator.vibrate(ms);}catch(e){}}
function checkAchievements(){
  const newly=[];
  const unlock=(id,cond)=>{if(cond&&!save.achievements.includes(id)){save.achievements.push(id);save.coins+=ACHIEVEMENTS[id].coins;newly.push(ACHIEVEMENTS[id].name);}};
  unlock('first',Object.values(save.correct).reduce((a,b)=>a+b,0)>=1);
  unlock('combo10',save.streakBest>=10);unlock('q100',save.totalQuestions>=100);unlock('boss5',save.bossWins>=5);unlock('sprintA',save.bestSprint>=24);unlock('perfect',save.bestSprint>=30);
  if(save.bestSprint>=30&&!save.ownedSkins.includes('30/30 légendaire'))save.ownedSkins.push('30/30 légendaire');
  persist();if(newly.length)later(250,()=>showToast(`SUCCÈS : ${newly.join(' · ')}`,2600));
}

function renderTitle(){clearTimers();scene='title';root.innerHTML=chrome(`<section class="screen"><div class="stars"></div><div class="title-scene"><div class="logo">MATH<br>QUEST</div><div class="subtitle">TERMINALE — LES AUTOMATISMES CONTRE-ATTAQUENT</div><div class="title-art">${heroHTML()}${bossHTML('Dérivation')}</div><p class="tagline">30 questions. 9 minutes. Une année pour devenir imbattable.</p><div class="title-actions"><button class="game-btn gold primary" data-action="hub">ENTRER DANS LA QUÊTE</button><button class="game-btn" data-action="tutorial">COMMENT JOUER</button><button class="game-btn" data-action="install">INSTALLATION iPHONE</button></div></div></section>`);}
function renderHub(){clearTimers();scene='hub';const priorities=save.weeklyTopics.join(' · ');root.innerHTML=chrome(`<section class="screen">${topbar('LE CAMP DE BASE','Choisis ta quête. Les bases ne disparaissent jamais.')}<div class="hub"><button class="game-btn quest" data-action="map"><strong>⚔ CAMPAGNE</strong><span>Carte des 36 semaines, mondes et boss.</span></button><button class="game-btn quest" data-action="sprint"><strong>⏱ 30 / 9 MIN</strong><span>Le format officiel : vitesse pure, 30 questions.</span></button><button class="game-btn quest" data-action="infinite"><strong>∞ DOJO</strong><span>Entraînement infini qui insiste sur tes faiblesses.</span></button><button class="game-btn quest" data-action="weekly"><strong>♛ BOSS HEBDO</strong><span>Combat basé sur le contrôle de cette semaine.</span></button><button class="game-btn quest" data-action="control"><strong>▣ CONTRÔLE</strong><span>Photo, analyse et thèmes prioritaires.</span></button><button class="game-btn quest" data-action="shop"><strong>✦ SKINS</strong><span>Gagne des pièces et transforme ton héros.</span></button><button class="game-btn quest" data-action="progress"><strong>📜 GRIMOIRE</strong><span>Maîtrise par notion, records et succès.</span></button><button class="game-btn quest" data-action="options"><strong>⚙ CHRONOMAGE</strong><span>Semaine réelle, son et sauvegarde.</span></button><div class="priority-ribbon">PRIORITÉ DE LA SEMAINE<br><b>${escapeHTML(priorities||'Aucun thème défini')}</b></div><button class="game-btn wide" data-action="tutorial">? TUTORIEL / RÈGLES DU JEU</button></div><button class="game-btn back-btn" data-action="title">← TITRE</button></section>`);}
function renderMap(){clearTimers();scene='map';let nodes='';TOPICS.forEach((t,i)=>{const unlocked=save.schoolWeek>=UNLOCK[t],mastered=(save.mastery[t]||0)>=.72;const top=34+i*63;nodes+=`<button class="world-node ${unlocked?'':'locked'} ${mastered?'mastered':''}" style="top:${top}px" ${unlocked?`data-story="${escapeHTML(t)}"`:'disabled'}><span class="short">${escapeHTML(SHORT[t])}</span>${escapeHTML(t)}<small>${unlocked?Math.round(save.mastery[t]*100)+'%':'S'+UNLOCK[t]}</small></button>`;});root.innerHTML=chrome(`<section class="screen">${topbar('CARTE DES 36 SEMAINES',`Semaine ${save.schoolWeek} · touche un monde accessible`)}<div class="map-wrap"><div class="world-map"><div class="road"></div>${nodes}</div></div><button class="game-btn back-btn" data-action="hub">← CAMP</button></section>`);}
function modeLabel(mode){return {sprint:'COURSE · 30 QUESTIONS / 9 MIN',infinite:'DOJO INFINI · ADAPTATIF',weekly:'BOSS DE LA SEMAINE',story:'COMBAT DE CAMPAGNE · 10 QUESTIONS'}[mode]||'ENTRAÎNEMENT';}
function startBattle(mode,topic=null){clearTimers();battle={mode,score:0,combo:0,playerHP:100,bossHP:100,qNumber:0,locked:false,topic,deadline:mode==='sprint'?Date.now()+540000:null,bossTopic:topic||(mode==='weekly'?pick(save.weeklyTopics.length?save.weeklyTopics:['Fondations']):chooseTopic())};scene='battle';renderBattleShell();nextQuestion();if(mode==='sprint'){const id=setInterval(updateTimer,250);timers.push(id);}}
function renderBattleShell(){const b=battle;root.innerHTML=chrome(`<section class="screen">${topbar('ARÈNE DE CALCUL',modeLabel(b.mode))}<div class="battle"><div class="battle-hud"><div class="hpbox"><div class="hp-label">TOI <span id="php">100</span>/100</div><div class="hp-track"><div id="pfill" class="hp-fill" style="width:100%"></div></div></div><div class="combo"><span id="timer">Q 0</span><br><span id="combo">COMBO ×1</span></div><div class="hpbox"><div class="hp-label">BOSS <span id="bhp">100</span>/100</div><div class="hp-track"><div id="bfill" class="hp-fill enemy" style="width:100%"></div></div></div></div><div class="arena"><div id="heroArena">${heroHTML()}</div><div id="bossArena">${bossHTML(b.bossTopic)}</div><div class="boss-caption">${escapeHTML(BOSSES[b.bossTopic][1])}</div></div><div class="question-box"><div id="qmeta" class="question-meta"></div><div id="qtext" class="question">Prépare-toi…</div></div><div class="answers" id="answers"></div></div></section>`);}
function updateBattleHUD(){if(!battle)return;const p=root.querySelector('#pfill'),bf=root.querySelector('#bfill'),ph=root.querySelector('#php'),bh=root.querySelector('#bhp'),co=root.querySelector('#combo');if(p)p.style.width=`${clamp(battle.playerHP,0,100)}%`;if(bf)bf.style.width=`${clamp(battle.bossHP,0,100)}%`;if(ph)ph.textContent=Math.max(0,Math.round(battle.playerHP));if(bh)bh.textContent=Math.max(0,Math.round(battle.bossHP));if(co)co.textContent=`COMBO ×${Math.max(1,battle.combo)}`;}
function updateTimer(){if(!battle||battle.mode!=='sprint'||scene!=='battle')return;const r=Math.max(0,Math.ceil((battle.deadline-Date.now())/1000)),el=root.querySelector('#timer');if(el)el.textContent=`${String(battle.qNumber).padStart(2,'0')}/30 · ${Math.floor(r/60)}:${String(r%60).padStart(2,'0')}`;if(r<=0)endBattle(true);}
function nextQuestion(){if(!battle||scene!=='battle')return;const b=battle;if(b.mode==='sprint'&&b.qNumber>=30)return endBattle(true);if(b.mode==='story'&&b.qNumber>=10)return endBattle(b.bossHP<=0||b.score>=6);if(b.mode==='weekly'&&(b.bossHP<=0||b.playerHP<=0||b.qNumber>=16))return endBattle(b.bossHP<=0);if(b.mode==='infinite'&&b.playerHP<=0)return endBattle(false);if(b.mode!=='sprint'&&(b.playerHP<=0||b.bossHP<=0))return endBattle(b.bossHP<=0);
  const forced=b.mode==='story'?b.topic:(b.mode==='weekly'?pick(save.weeklyTopics.length?save.weeklyTopics:['Fondations']):null);currentQ=newQuestion(forced);b.qNumber++;b.locked=false;
  const qm=root.querySelector('#qmeta'),qt=root.querySelector('#qtext'),ans=root.querySelector('#answers');if(!qm||!qt||!ans)return;qm.textContent=`${currentQ.topic.toUpperCase()} · DIFFICULTÉ ${difficulty(currentQ.topic)}`;qt.textContent=currentQ.q;ans.innerHTML=currentQ.opts.map((o,i)=>`<button class="game-btn answer" data-answer="${i}"><b>${String.fromCharCode(65+i)}</b> — ${escapeHTML(o)}</button>`).join('')+`<div class="feedback" id="feedback">${b.mode==='sprint'?'Réponds vite. Aucune correction longue pendant la course.':'Touche une réponse. Les notions faibles reviendront plus souvent.'}</div>`;if(b.mode!=='sprint'){const t=root.querySelector('#timer');if(t)t.textContent=`QUESTION ${b.qNumber}`;}else updateTimer();
}
function answer(i){if(!battle||battle.locked||!currentQ||scene!=='battle')return;battle.locked=true;const good=i===currentQ.idx,t=currentQ.topic;save.attempts[t]++;save.totalQuestions++;const buttons=[...root.querySelectorAll('[data-answer]')];const feedback=root.querySelector('#feedback');if(good){save.correct[t]++;battle.score++;battle.combo++;const dmg=Math.min(34,11+battle.combo*2);battle.bossHP-=dmg;save.mastery[t]=clamp(save.mastery[t]+.022*(1-save.mastery[t])+.008,.05,.98);if(buttons[i])buttons[i].classList.add('good');if(feedback)feedback.textContent=`${pick(GOOD)} −${dmg} PV`;const ba=root.querySelector('#bossArena .boss');if(ba){ba.classList.add('hit');later(260,()=>ba.classList.remove('hit'));}beep(680,.07,'square');vibrate(18);}else{battle.combo=0;const dmg=battle.mode==='sprint'?7:14;battle.playerHP-=dmg;save.mastery[t]=clamp(save.mastery[t]-.035*save.mastery[t],.05,.98);if(buttons[i])buttons[i].classList.add('bad');if(buttons[currentQ.idx])buttons[currentQ.idx].classList.add('good');if(feedback)feedback.textContent=`${pick(BAD)} Réponse : ${currentQ.opts[currentQ.idx]}. ${currentQ.ex}`;const ha=root.querySelector('#heroArena .hero');if(ha){ha.classList.add('hit');later(260,()=>ha.classList.remove('hit'));}beep(170,.12,'sawtooth');vibrate(55);}save.streakBest=Math.max(save.streakBest,battle.combo);persist();updateBattleHUD();checkAchievements();later(battle.mode==='sprint'?440:(good?900:1800),nextQuestion);}
function endBattle(victory){if(!battle||scene!=='battle')return;clearTimers();const b=battle,mode=b.mode,score=b.score,qn=Math.max(1,b.qNumber);let reward=0,xp=0;if(mode==='sprint'){save.bestSprint=Math.max(save.bestSprint,score);reward=score*4+(score>=25?70:0);xp=score*8;victory=score>=20;}else if(mode==='story'){reward=victory?70:20;xp=victory?120:45;}else if(mode==='weekly'){reward=victory?140:35;xp=victory?210:60;}else{reward=Math.max(10,score*3);xp=Math.max(20,score*5);}if(victory&&['story','weekly'].includes(mode))save.bossWins++;save.coins+=reward;save.xp+=xp;save.level=1+Math.floor(save.xp/500);persist();checkAchievements();renderResult(victory,reward,xp,score,qn,mode,b.topic);}
function renderResult(victory,reward,xp,score,qn,mode,topic){scene='result';const denom=mode==='sprint'?30:qn,rank=mode==='sprint'?(score>=28?'S':score>=24?'A':score>=19?'B':'C'):'';root.innerHTML=chrome(`<section class="screen"><div class="stars"></div><div class="result"><h2>${victory?'VICTOIRE !':'RETRAITE STRATÉGIQUE'}</h2>${heroHTML()}<div class="score">${score} bonne(s) réponse(s) sur ${denom}</div><div class="loot">+ ${xp} XP · + ${reward} ◈</div>${mode==='sprint'?`<div class="rank">RANG ${rank} · RECORD ${save.bestSprint}/30</div>`:''}<div class="result-actions"><button class="game-btn gold" data-replay="${mode}" data-topic="${escapeHTML(topic||'')}">REJOUER</button><button class="game-btn" data-action="hub">CAMP DE BASE</button></div></div></section>`);}
function renderShop(){clearTimers();scene='shop';let rows='';Object.entries(SKINS).forEach(([name,s])=>{const owned=save.ownedSkins.includes(name),active=save.skin===name,afford=save.coins>=s.price;rows+=`<div class="shop-row"><div class="skin-mini" style="--skin-body:${s.body};--skin-accent:${s.accent};--skin-cape:${s.cape}"></div><div><div class="row-title">${escapeHTML(name)}</div><div class="row-sub">${active?'ÉQUIPÉ':owned?'POSSÉDÉ':`${s.price} ◈`}${name==='30/30 légendaire'?' · offert après 30/30':''}</div></div>${active?'':owned?`<button class="game-btn mini-btn" data-equip="${escapeHTML(name)}">ÉQUIPER</button>`:`<button class="game-btn mini-btn" data-buy="${escapeHTML(name)}" ${afford?'':'disabled'}>ACHETER</button>`}</div>`;});root.innerHTML=chrome(`<section class="screen">${topbar('ÉCHOPPE DE L’ALCHIMISTE','Les skins changent réellement ton héros.')}<div class="panel-screen"><div class="stats-strip">BOURSE : ◈ ${save.coins} · SKIN ACTUEL : ${escapeHTML(save.skin)}</div>${rows}</div><button class="game-btn back-btn" data-action="hub">← CAMP</button></section>`);}
function renderProgress(){clearTimers();scene='progress';let rows='';TOPICS.forEach(t=>{const m=save.mastery[t]||0,att=save.attempts[t]||0,ok=save.correct[t]||0;rows+=`<div class="progress-row"><div class="row-title">${escapeHTML(t)}</div><div class="meter"><i class="${m>=.7?'high':''}" style="width:${Math.round(m*100)}%"></i></div><div class="progress-number">${Math.round(m*100)}%<br>${ok}/${att}</div></div>`;});let ach='';Object.entries(ACHIEVEMENTS).forEach(([id,a])=>{const on=save.achievements.includes(id);ach+=`<div class="achievement-row" style="grid-template-columns:42px 1fr 54px"><div style="font-size:25px">${on?'★':'☆'}</div><div><div class="row-title">${escapeHTML(a.name)}</div><div class="row-sub">${escapeHTML(a.desc)}</div></div><div class="progress-number">${on?'FAIT':`+${a.coins}◈`}</div></div>`;});root.innerHTML=chrome(`<section class="screen">${topbar('GRIMOIRE DE PROGRESSION','Le jeu favorise tes faiblesses sans oublier les bases.')}<div class="panel-screen"><div class="stats-strip">QUESTIONS : ${save.totalQuestions} · BOSS : ${save.bossWins} · MEILLEURE COURSE : ${save.bestSprint}/30 · COMBO MAX : ×${save.streakBest}</div>${rows}<div class="field-title">SUCCÈS</div>${ach}</div><button class="game-btn back-btn" data-action="hub">← CAMP</button></section>`);}

const db = {
  open(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){resolve(null);return;}const r=indexedDB.open('MathQuestDB',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});},
  async put(key,val){try{const d=await this.open();if(!d)return;await new Promise((res,rej)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put(val,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});}catch(e){}},
  async get(key){try{const d=await this.open();if(!d)return null;return await new Promise((res,rej)=>{const tx=d.transaction('files','readonly'),r=tx.objectStore('files').get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error);});}catch(e){return null;}}
};
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file);});}
function normalize(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function topicsFromText(text){const n=normalize(text), scores={};TOPICS.forEach(t=>scores[t]=0);for(const [t,words] of Object.entries(KEYWORDS)){words.forEach(w=>{const nw=normalize(w);if(n.includes(nw))scores[t]++;});}return TOPICS.filter(t=>scores[t]>0).sort((a,b)=>scores[b]-scores[a]);}
async function loadSavedControlImage(){const b=await db.get('weekly-control');if(b instanceof Blob){currentControlBlob=b;try{currentControlDataURL=await fileToDataURL(b);}catch(e){}}}
function renderControl(){clearTimers();scene='control';const toggles=TOPICS.map(t=>`<button class="topic-toggle ${save.weeklyTopics.includes(t)?'active':''}" data-topic-toggle="${escapeHTML(t)}">${escapeHTML(t)}</button>`).join('');root.innerHTML=chrome(`<section class="screen">${topbar('ATELIER DU CONTRÔLE','La photo guide le boss de la semaine.')}<div class="panel-screen control-grid"><div class="field-title">1 · PHOTO / SCAN DU CONTRÔLE</div><label class="game-btn gold file-label">📷 PRENDRE / CHOISIR UNE PHOTO<input id="controlFile" type="file" accept="image/*" capture="environment"></label><div class="control-preview" id="controlPreview">${currentControlDataURL?`<img src="${currentControlDataURL}" alt="Aperçu du contrôle">`:escapeHTML(save.lastControlName||'Aucune photo importée')}</div><div class="two-actions"><button class="game-btn" data-action="ocr" ${currentControlDataURL?'':'disabled'}>ANALYSER LA PHOTO</button><button class="game-btn" data-action="clear-photo" ${currentControlDataURL?'':'disabled'}>EFFACER</button></div><div id="ocrStatus" class="ocr-status">L’analyse OCR est facultative et nécessite Internet. Sur iPhone, l’import peut ouvrir directement l’appareil photo. Si l’OCR échoue, sélectionne simplement les thèmes ci-dessous.</div><div class="field-title">2 · THÈMES PRIORITAIRES</div><div class="topic-grid" id="topicGrid">${toggles}</div><div class="two-actions"><button class="game-btn gold" data-action="save-topics">ENREGISTRER</button><button class="game-btn" data-action="weekly">AFFRONTER LE BOSS</button></div></div><button class="game-btn back-btn" data-action="hub">← CAMP</button></section>`);const input=root.querySelector('#controlFile');if(input)input.addEventListener('change',handleControlFile);}
async function handleControlFile(e){const f=e.target.files&&e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){showToast('Choisis une image du contrôle.');return;}if(f.size>18*1024*1024){showToast('Image trop lourde : choisis une photo de moins de 18 Mo.');return;}currentControlBlob=f;currentControlDataURL=await fileToDataURL(f);save.lastControlName=f.name||'Photo du contrôle';persist();await db.put('weekly-control',f);renderControl();showToast('Photo enregistrée sur cet iPhone.');}
function updateTopicToggleDOM(){root.querySelectorAll('[data-topic-toggle]').forEach(b=>b.classList.toggle('active',save.weeklyTopics.includes(b.dataset.topicToggle)));}
async function clearPhoto(){currentControlDataURL='';currentControlBlob=null;save.lastControlName='';persist();await db.put('weekly-control',new Blob([]));renderControl();}
function loadScriptOnce(src){return new Promise((resolve,reject)=>{if(window.Tesseract){resolve();return;}const found=document.querySelector(`script[data-src="${src}"]`);if(found){found.addEventListener('load',resolve,{once:true});found.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src=src;s.async=true;s.dataset.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Chargement OCR impossible'));document.head.appendChild(s);});}
async function runOCR(){if(!currentControlDataURL)return;const status=root.querySelector('#ocrStatus');if(status)status.textContent='Chargement du lecteur de texte…';if(!navigator.onLine){if(status)status.textContent='Hors ligne : utilise la sélection manuelle des thèmes.';return;}try{await loadScriptOnce('https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js');if(!window.Tesseract)throw new Error('OCR non chargé');if(status)status.textContent='Analyse de la photo… cela peut prendre un moment sur iPhone.';const result=await window.Tesseract.recognize(currentControlDataURL,'fra',{logger:m=>{if(status&&m&&m.status){const p=m.progress?` ${Math.round(m.progress*100)}%`:'';status.textContent=`OCR : ${m.status}${p}`;}}});const text=result?.data?.text||'',found=topicsFromText(text);if(found.length){save.weeklyTopics=found.slice(0,7);persist();updateTopicToggleDOM();if(status)status.textContent=`Détecté : ${save.weeklyTopics.join(', ')}. Vérifie les thèmes puis enregistre.`;showToast('Thèmes détectés !');}else{if(status)status.textContent='Aucun thème détecté avec assez de confiance. Sélectionne-les manuellement.';}}catch(e){if(status)status.textContent='OCR indisponible ou bloqué. La photo reste enregistrée : sélectionne les thèmes manuellement.';}}

function renderOptions(){clearTimers();scene='options';root.innerHTML=chrome(`<section class="screen">${topbar('OPTIONS DU CHRONOMAGE','Fais coïncider le jeu avec ta vraie classe.')}<div class="panel-screen"><div class="field-title">SEMAINE DE L’ANNÉE SCOLAIRE</div><div class="week-display" id="weekDisplay">${save.schoolWeek} / 36</div><input class="week-slider" id="weekRange" type="range" min="1" max="36" value="${save.schoolWeek}"><p class="ocr-status">Les nouveaux chapitres apparaissent progressivement. Fondations, fractions et équations continuent toujours à revenir.</p><button class="game-btn gold" style="width:100%;margin-top:8px" data-action="save-week">SAUVEGARDER LA SEMAINE</button><div class="toggle-line"><div><b>SONS ARCADE</b><div class="row-sub">Petits effets sonores générés localement.</div></div><input id="soundToggle" type="checkbox" ${save.sound?'checked':''}></div><div class="install-card"><b>SAUVEGARDE LOCALE</b><br>XP, pièces, progression et thèmes sont conservés sur l’appareil. La photo du contrôle est stockée séparément dans le navigateur.</div><div class="danger-zone"><div class="field-title">ZONE DANGEREUSE</div><button class="game-btn red" style="width:100%" data-action="reset">RÉINITIALISER TOUTE LA PARTIE</button></div></div><button class="game-btn back-btn" data-action="hub">← CAMP</button></section>`);const range=root.querySelector('#weekRange');if(range)range.addEventListener('input',()=>{root.querySelector('#weekDisplay').textContent=`${range.value} / 36`;});const sound=root.querySelector('#soundToggle');if(sound)sound.addEventListener('change',()=>{save.sound=sound.checked;persist();beep(520,.06);});}
function renderTutorial(){clearTimers();scene='tutorial';root.innerHTML=chrome(`<section class="screen">${topbar('MANUEL DU HÉROS','Tout le jeu en 90 secondes.')}<div class="tutorial"><div class="tutorial-page"><span class="big">⚔</span><h3>1 · LE BUT</h3><p>Réponds vite aux questions pour infliger des dégâts. Une erreur te blesse. Plus ton combo monte, plus tes attaques sont fortes.</p></div><div class="tutorial-page"><span class="big">⏱</span><h3>2 · COURSE 30 / 9</h3><p>30 questions, 9 minutes. Le chrono ne s’arrête pas. Le rang S commence à 28/30 ; ton record est enregistré.</p></div><div class="tutorial-page"><span class="big">🗺</span><h3>3 · CAMPAGNE</h3><p>Les 13 mondes se débloquent sur 36 semaines. On ne suppose pas la Seconde/Première maîtrisée : les fondations restent dans le mélange pendant toute l’année.</p></div><div class="tutorial-page"><span class="big">🧠</span><h3>4 · ADAPTATION</h3><p>Chaque thème possède une maîtrise. Une notion faible revient davantage ; une notion maîtrisée monte en difficulté. Les thèmes du contrôle hebdomadaire ont un poids renforcé.</p></div><div class="tutorial-page"><span class="big">📷</span><h3>5 · CONTRÔLE DE LA SEMAINE</h3><p>Prends une photo ou choisis-la dans Photos. L’OCR peut repérer les chapitres si Internet est disponible ; tu peux toujours corriger les thèmes manuellement.</p></div><div class="tutorial-page"><span class="big">✦</span><h3>6 · RÉCOMPENSES</h3><p>Gagne XP et pièces, débloque des succès, achète des skins. Un 30/30 débloque automatiquement le skin légendaire.</p></div><button class="game-btn gold" style="width:100%" data-action="hub">COMMENCER À JOUER</button></div><button class="game-btn back-btn" data-action="title">← TITRE</button></section>`);save.tutorialSeen=true;persist();}
function renderInstall(){clearTimers();scene='install';const standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;root.innerHTML=chrome(`<section class="screen">${topbar('INSTALLATION iPHONE','Math Quest peut apparaître comme une vraie app.')}<div class="panel-screen"><div class="install-card"><b>${standalone?'✓ TU ES DÉJÀ EN MODE APP':'INSTALLATION DEPUIS SAFARI'}</b><br><br>1. Ouvre cette page dans <b>Safari</b>.<br>2. Touche <b>Partager</b>.<br>3. Choisis <b>Sur l’écran d’accueil</b>.<br>4. Active <b>Ouvrir comme app web</b>.<br>5. Touche <b>Ajouter</b>.<br><br>L’icône Math Quest apparaît sur l’écran d’accueil. Le jeu principal fonctionne ensuite hors ligne après un premier chargement complet.</div><div class="tutorial-page"><h3>PHOTO DU CONTRÔLE</h3><p>Dans Atelier du contrôle, le bouton photo peut proposer directement l’appareil photo de l’iPhone. L’OCR demande Internet ; la sélection manuelle reste toujours disponible.</p></div><div class="tutorial-page"><h3>IMPORTANT</h3><p>Une PWA doit être ouverte depuis une adresse web HTTPS pour être installée. Le ZIP fourni contient tout le jeu ; le fichier README explique comment le publier gratuitement en quelques minutes.</p></div><button class="game-btn gold" style="width:100%" data-action="hub">ALLER AU CAMP</button></div><button class="game-btn back-btn" data-action="title">← TITRE</button></section>`);}

function buySkin(name){const s=SKINS[name];if(!s||save.ownedSkins.includes(name))return;if(save.coins<s.price){showToast('Pas assez de pièces.');return;}save.coins-=s.price;save.ownedSkins.push(name);save.skin=name;persist();beep(780,.12);renderShop();}
function equipSkin(name){if(!save.ownedSkins.includes(name))return;save.skin=name;persist();beep(560,.07);renderShop();}
function saveTopics(){if(!save.weeklyTopics.length){showToast('Choisis au moins un thème.');return;}persist();showToast('Priorités de la semaine enregistrées.');}
function resetGame(){modal('EFFACER LA PARTIE ?','XP, pièces, skins, statistiques et maîtrise seront remis à zéro.','OUI, EFFACER','ANNULER',()=>{save=defaults();persist();currentControlDataURL='';currentControlBlob=null;db.put('weekly-control',new Blob([]));renderTitle();});}

function route(action){beep(300,.025,'square');switch(action){case'title':renderTitle();break;case'hub':renderHub();break;case'map':renderMap();break;case'sprint':startBattle('sprint');break;case'infinite':startBattle('infinite');break;case'weekly':startBattle('weekly');break;case'control':renderControl();break;case'shop':renderShop();break;case'progress':renderProgress();break;case'options':renderOptions();break;case'tutorial':renderTutorial();break;case'install':renderInstall();break;case'ocr':runOCR();break;case'clear-photo':clearPhoto();break;case'save-topics':saveTopics();break;case'save-week':{const r=root.querySelector('#weekRange');if(r){save.schoolWeek=clamp(parseInt(r.value,10)||1,1,36);persist();showToast(`Semaine ${save.schoolWeek} enregistrée.`);}break;}case'reset':resetGame();break;}}
root.addEventListener('click',e=>{const answerBtn=e.target.closest('[data-answer]');if(answerBtn){answer(parseInt(answerBtn.dataset.answer,10));return;}const story=e.target.closest('[data-story]');if(story){startBattle('story',story.dataset.story);return;}const replay=e.target.closest('[data-replay]');if(replay){const topic=replay.dataset.topic||null;startBattle(replay.dataset.replay,topic);return;}const equip=e.target.closest('[data-equip]');if(equip){equipSkin(equip.dataset.equip);return;}const buy=e.target.closest('[data-buy]');if(buy){buySkin(buy.dataset.buy);return;}const tt=e.target.closest('[data-topic-toggle]');if(tt){const t=tt.dataset.topicToggle,i=save.weeklyTopics.indexOf(t);if(i>=0)save.weeklyTopics.splice(i,1);else save.weeklyTopics.push(t);tt.classList.toggle('active');beep(430,.03);return;}const act=e.target.closest('[data-action]');if(act&&!act.disabled)route(act.dataset.action);});
root.addEventListener('keydown',e=>{if(scene==='battle'&&!/input|textarea|select/i.test(e.target.tagName)){const k=e.key.toLowerCase(),idx='abcd'.indexOf(k);if(idx>=0){e.preventDefault();answer(idx);}}});

window.__MQTEST={generate:(topic,d)=>GEN[topic](d),topics:[...TOPICS]};
async function init(){await loadSavedControlImage();if('serviceWorker'in navigator&&location.protocol.startsWith('http')){try{await navigator.serviceWorker.register('./sw.js');}catch(e){}}renderTitle();}
init();
})();
